---
- name: Configure macOS
  hosts: localhost
  
  vars:
    dockitems_remove:
      - TV
      - Podcasts
      - Mail
      - Maps
      - FaceTime
      - Calendar
      - Contacts
      - Reminders
      - Notes
      - Freeform
      - News
      - Photos
      - Safari
      - Messages
      - 'App Store'
      - 'System Settings'

    dockitems_persist:
      - name: "Brave"
        path: "/Applications/Brave Browser.app/"
        pos: 2
      - name: "Discord Canary"
        path: "/Applications/Discord Canary.app"
        pos: 3
      - name: "Sublime Text"
        path: "/Applications/Sublime Text.app/"
        pos: 4
      - name: "Zed"
        path: "/Applications/Zed.app"
        pos: 5
      - name: "Warp"
        path: "/Applications/Warp.app"
        pos: 6
      - name: "Music"
        path: "/Applications/Music.app"
        pos: 7
      - name: "Settings"
        path: "/Applications/System Settings.app"
        pos: 8



  tasks:
    - name: Update Homebrew
      command: brew update
      changed_when: false

    - name: Install common software with Homebrew
      homebrew:
        name:
          - git
        state: present

    - name: Install Homebrew casks (GUI apps)
      homebrew_cask:
        name:
          - brave-browser
          - clip-studio-paint
          - discord@canary
          - handbrake
          - jellyfin-media-player
          - linearmouse
          - microsoft-office-buisnesspro
          - parsec
          - sublime-text
          - slack
          - transmit
          - vmware-fusion
          - warp
          - zed
        state: present

    - name: Set macOS dock to auto-hide
      shell: defaults write com.apple.dock autohide -bool true && killall Dock
      changed_when: false

    - name: Ensure .zshrc exists
      file:
        path: ~/.zshrc
        state: touch
        mode: "0644"

    - name: Add custom alias to .zshrc
      lineinfile:
        path: ~/.zshrc
        line: 'alias ll="ls -la"'
        state: present

    - name: download dotfiles from github
      git:
        repo: https://github.com/lavavex/dotfiles.git
        dest: ~/dotfiles
        clone: true
        force: true
      changed_when: false

    - name: Download .osx script from github
      get_url:
        url: https://raw.githubusercontent.com/lavavex/dotfiles/refs/heads/main/.osx
        dest: ~/dotfiles/.osx
        mode: "0755"
      changed_when: false

    - name: Run .osx script
      shell: "~/dotfiles/.osx --no-restart"
      changed_when: false
      ignore_errors: true

    - name: Docking
      import_role:
        name: geerlingguy.mac.dock

    - name: MAS
      community.general.mas:
        id:
          - 1451685025 #Wireguard-GUI
          - 441258766 #Magnet
        state: present
        upgrade_all: true

